spring.application.name=netflix-eureka

server.port=8761

spring.security.user.name=eureka-user
spring.security.user.password=zvBGTYdMUJV7mpRs35YA

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false